name: Fetch Jira Child Issues

on:
  issues:
    types: [opened, reopened]  # Runs when a new GitHub issue is created (manually or by script)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  fetch-jira-child-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue Key from GitHub Issue Title
        id: extract_key
        run: |
          TITLE="${{ github.event.issue.title }}"
          JIRA_KEY=$(echo "$TITLE" | grep -oE '[A-Z0-9]+-[0-9]+')
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV

      - name: Fetch Jira Child Issues with Full Details
        id: fetch_child_issues
        if: env.JIRA_KEY != ''
        run: |
          RESPONSE=$(curl -s -u "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            -X GET "https://shaifimran.atlassian.net/rest/api/3/search?jql=parent=${{ env.JIRA_KEY }}" \
            -H "Accept: application/json")

          echo "$RESPONSE" > jira_child_issues.json

      - name: Create GitHub Issues for Child Issues
        run: |
          cat jira_child_issues.json | jq -c '.issues[]' | while read -r issue; do
            CHILD_KEY=$(echo "$issue" | jq -r '.key')
            SUMMARY=$(echo "$issue" | jq -r '.fields.summary')
            DESCRIPTION=$(echo "$RESPONSE" | jq -r '.fields.description.content | map(.content | map(.text) | join(" ")) | join("\n")'

            PRIORITY=$(echo "$issue" | jq -r '.fields.priority.name')
            STATUS=$(echo "$issue" | jq -r '.fields.status.name')
            ISSUE_TYPE=$(echo "$issue" | jq -r '.fields.issuetype.name')

            # Create GitHub Issue for the child Jira issue
            GH_ISSUE_RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              -d "{
                \"title\": \"$[${CHILD_KEY}] {SUMMARY}\",
                \"body\": \"### Parent Issue: [${{ env.JIRA_KEY }}](https://shaifimran.atlassian.net/browse/${{ env.JIRA_KEY }})\n\n**Jira Issue:** [${CHILD_KEY}](https://shaifimran.atlassian.net/browse/${CHILD_KEY})\n\n**Issue Type:** ${ISSUE_TYPE}\n\n**Priority:** ${PRIORITY}\n\n**Status:** ${STATUS}\n\n**Summary:** ${SUMMARY}\n\n**Description:** ${DESCRIPTION}\"
              }")

            CHILD_ISSUE_NUMBER=$(echo "$GH_ISSUE_RESPONSE" | jq -r '.number')

            # Trigger workflow for the newly created issue
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/fetch_jira_child_issues.yml/dispatches \
              -d "{\"ref\": \"main\", \"inputs\": {\"issue_number\": \"$CHILD_ISSUE_NUMBER\"}}"

            echo "Triggered workflow for child issue: $CHILD_KEY"
          done
